version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres_kinopoisk"
    ports:
      - "54325:5432"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nameuser -d namedb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 4G
# volumes:
#   my_dbdata:

# run_ docker-compose up -d
# view_conteiners_ docker ps -a 
# in_container_ docker exec -it "name_conteiner" bash
# doc_docker_ https://docs.docker.com/samples/postgres/ 